### ISSUE TITLE
役職テンプレート/Role Temple

### ISSUE THREAD

**Issue by Shanpan2** [supeshio/TheSpaceRoles#5]
### 陣営
- [ ] インポスター陣営/Impostor Roles
- [ ] クルーメイト陣営/Crewmate Roles
- [ ] 第三陣営/Neutral Roles
- [ ] 属性/Add-ons
## その他/Other

※役職名に関してはできれば英語名もつけてください。

**Comment by Ks-777** [comment]
これって.githubのISSUE_TEMPLATEに追加するんですか?

**Comment by Shanpan2** [comment]
あーできればしてほしいかなあ(スぺ塩さんの判断次第)

**Comment by Ks-777** [comment]
今バグ報告のやーつも作ってるんで一緒に突っ込んどきます

**Comment by Ks-777** [comment]
とりあえずできたのでクローズします。 あざした
